### Since governor elections are recorded at the county-level, we first wanted to see the performace of each respective county, and then check how the voting patterns add up to the overall state election outcome.

#### Specifically, we are looking at whether the political party that wins the most influential counties also happens to win the state as a whole. Furthermore, we define "influential" counties by determing the counties with the largest share of total votes in each state.

In [2]:
# importing packages
import numpy as np
import pandas as pd

# reading in files
governors_county_candidate = pd.read_csv("4-US_Election_2020/governors_county_candidate.csv")
governors_county = pd.read_csv("4-US_Election_2020/governors_county.csv")
governors_state = pd.read_csv("4-US_Election_2020/governors_state.csv")

president_county_candidate = pd.read_csv("4-US_Election_2020/president_county_candidate.csv")
president_county = pd.read_csv("4-US_Election_2020/president_county.csv")
president_state = pd.read_csv("4-US_Election_2020/president_state.csv")

#### **Sub Question 1:** Which counties are the most influential in each state's gubernatorial election based on their share of total votes?

In [3]:
county_votes = (governors_county
                .groupby(["state", "county"])
                .agg(total_votes=("total_votes", "max"))
                .reset_index())

state_votes = governors_state.copy()
df = county_votes.merge(state_votes, on="state")
df["vote_share"] = df["total_votes"] / df["votes"]

df_top = (df
          .sort_values(["state", "vote_share"], ascending=[True, False])
          .groupby("state")
          .head(5))

df_top_sorted = df_top.sort_values(
    by=["state", "vote_share"], 
    ascending=[True, False]
).reset_index(drop=True)

df_top_sorted[["state", "county", "vote_share"]]

             state                  county  vote_share
0         Delaware       New Castle County    0.583866
1         Delaware           Sussex County    0.262572
2         Delaware             Kent County    0.176652
3          Indiana           Marion County    0.129405
4          Indiana             Lake County    0.072824
5          Indiana         Hamilton County    0.064230
6          Indiana            Allen County    0.055980
7          Indiana       St. Joseph County    0.038153
8         Missouri        St. Louis County    0.178087
9         Missouri          Jackson County    0.110898
10        Missouri      St. Charles County    0.073696
11        Missouri           Greene County    0.047074
12        Missouri          St. Louis city    0.044608
13         Montana      Yellowstone County    0.139349
14         Montana         Missoula County    0.119264
15         Montana         Gallatin County    0.118470
16         Montana         Flathead County    0.099833
17         Montana  Lewis and Clark County    0.070427
18   New Hampshire              Manchester    0.066354
19   New Hampshire                  Nashua    0.057115
20   New Hampshire                 Concord    0.030115
21   New Hampshire                   Dover    0.024254
22   New Hampshire                   Derry    0.022571
23  North Carolina             Wake County    0.114820
24  North Carolina      Mecklenburg County    0.103049
25  North Carolina         Guilford County    0.051699
26  North Carolina          Forsyth County    0.036575
27  North Carolina           Durham County    0.032695
28    North Dakota             Cass County    0.253007
29    North Dakota         Burleigh County    0.149220
30    North Dakota      Grand Forks County    0.091056
31    North Dakota             Ward County    0.083047
32    North Dakota           Morton County    0.048862
33            Utah        Salt Lake County    0.370810
34            Utah             Utah County    0.194866
35            Utah            Davis County    0.116400
36            Utah            Weber County    0.076362
37            Utah       Washington County    0.062004
38         Vermont              Burlington    0.061255
39         Vermont                   Essex    0.036983
40         Vermont        South Burlington    0.034931
41         Vermont              Colchester    0.026451
42         Vermont                 Rutland    0.022056
43      Washington             King County    0.298415
44      Washington           Pierce County    0.114406
45      Washington        Snohomish County    0.108172
46      Washington          Spokane County    0.072830
47      Washington            Clark County    0.067893
48   West Virginia          Kanawha County    0.105768
49   West Virginia         Berkeley County    0.066276
50   West Virginia       Monongalia County    0.054106
51   West Virginia             Wood County    0.049849
52   West Virginia           Cabell County    0.048046

##### We calculated each county's share of total votes within it's state to determine its level of influence in the gubernatorial election. Each county was ranked by it's total vote share, and then the top 5 counties in each state were chosen as being the most influential as they provide the larget amount of votes to the total election results for their state.

#### **Sub Question 2:** Which political party tends to dominate in the most influential counties across each state?

In [4]:
state = governors_state

data = county_votes.merge(state, on="state")

data["share"] = data["total_votes"] / data["votes"]

top = (data
       .sort_values(["state", "share"], ascending=[True, False])
       .groupby("state")
       .head(5))

winners = governors_county_candidate[
    governors_county_candidate["won"] == True
]

top_party = top.merge(winners, on=["state", "county"])

top_party = top_party.rename(columns={"party_y": "party"})

top_party_sorted = (top_party
                    .sort_values(["state", "share"], ascending=[True, False])
                    .reset_index(drop=True))

top_party_sorted[["state", "county", "party"]]

             state                  county party
0         Delaware       New Castle County   DEM
1         Delaware           Sussex County   REP
2         Delaware             Kent County   DEM
3          Indiana           Marion County   DEM
4          Indiana             Lake County   DEM
5          Indiana         Hamilton County   REP
6          Indiana            Allen County   REP
7          Indiana       St. Joseph County   REP
8         Missouri        St. Louis County   DEM
9         Missouri          Jackson County   DEM
10        Missouri      St. Charles County   REP
11        Missouri           Greene County   REP
12        Missouri          St. Louis city   DEM
13         Montana      Yellowstone County   REP
14         Montana         Missoula County   DEM
15         Montana         Gallatin County   DEM
16         Montana         Flathead County   REP
17         Montana  Lewis and Clark County   DEM
18   New Hampshire              Manchester   REP
19   New Hampshire                  Nashua   REP
20   New Hampshire                 Concord   REP
21   New Hampshire                   Dover   REP
22   New Hampshire                   Derry   REP
23  North Carolina             Wake County   DEM
24  North Carolina      Mecklenburg County   DEM
25  North Carolina         Guilford County   DEM
26  North Carolina          Forsyth County   DEM
27  North Carolina           Durham County   DEM
28    North Dakota             Cass County   REP
29    North Dakota         Burleigh County   REP
30    North Dakota      Grand Forks County   REP
31    North Dakota             Ward County   REP
32    North Dakota           Morton County   REP
33            Utah        Salt Lake County   REP
34            Utah             Utah County   REP
35            Utah            Davis County   REP
36            Utah            Weber County   REP
37            Utah       Washington County   REP
38         Vermont              Burlington   DEM
39         Vermont                   Essex   REP
40         Vermont        South Burlington   REP
41         Vermont              Colchester   REP
42         Vermont                 Rutland   REP
43      Washington             King County   DEM
44      Washington           Pierce County   DEM
45      Washington        Snohomish County   DEM
46      Washington          Spokane County   REP
47      Washington            Clark County   DEM
48   West Virginia          Kanawha County   REP
49   West Virginia         Berkeley County   REP
50   West Virginia       Monongalia County   REP
51   West Virginia             Wood County   REP
52   West Virginia           Cabell County   REP

#### After determing the top 5 most influential counties in each state's gubernatorial elections based on vote share, we then determined the political party of those counties. This allows us to see which party dominates in the most influential counties across each state.

#### **Sub Question 3:** Do the political party preferences of the top 5 counties match the overall state election outcome?

In [5]:
data = county_votes.merge(governors_state, on="state")
data["share"] = data["total_votes"] / data["votes"]

top = (data
       .sort_values(["state", "share"], ascending=[True, False])
       .groupby("state")
       .head(5))

winners = governors_county_candidate[
    governors_county_candidate["won"] == True
]

top_party = top.merge(winners, on=["state", "county"])

top5_party = (top_party
              .groupby(["state", "party"])
              .size()
              .reset_index(name="count")
              .sort_values(["state", "count"], ascending=[True, False])
              .groupby("state")
              .head(1)
              .rename(columns={"party": "top5_party"}))

state_winner = (governors_county_candidate
                .groupby(["state", "party"])["votes"]
                .sum()
                .reset_index()
                .sort_values(["state", "votes"], ascending=[True, False])
                .groupby("state")
                .head(1)
                .rename(columns={"party": "state_winner"}))

result = top5_party.merge(state_winner[["state", "state_winner"]], on="state")
result["aligns"] = result["top5_party"] == result["state_winner"]

display(result)

             state top5_party  count state_winner  aligns
0         Delaware        DEM      2          DEM    True
1          Indiana        REP      3          REP    True
2         Missouri        DEM      3          REP   False
3          Montana        DEM      3          REP   False
4    New Hampshire        REP      5          REP    True
5   North Carolina        DEM      5          DEM    True
6     North Dakota        REP      5          REP    True
7             Utah        REP      5          REP    True
8          Vermont        REP      4          REP    True
9       Washington        DEM      4          DEM    True
10   West Virginia        REP      5          REP    True

#### We then compared the dominant political party in the top 5 most influential counties to the overall winner in the gubertorial elections for each state. We did this as it allowed us to determine whether the voting patterns in the deemed most impactful counties align witht the statewide results. Out of the 11 states listed, 9 states showed alignment, illustrating that the political party dominating the most influential counties is mostly reflected in the overall results.

#### **Overall:** Do the most influential counties in gubernatorial elections also reflect the outcome of presidential elections in each state?

In [6]:
pres_winner = (president_county_candidate
               .groupby(["state", "party"])["total_votes"]
               .sum()
               .reset_index()
               .sort_values(["state", "total_votes"], ascending=[True, False])
               .groupby("state")
               .head(1)
               .rename(columns={"party": "pres_winner"}))

result = result.merge(pres_winner[["state", "pres_winner"]], on="state")
result["aligns_president"] = result["top5_party"] == result["pres_winner"]
result[["state", "top5_party", "state_winner", "pres_winner", "aligns", "aligns_president"]]

,state,top5_party,state_winner,pres_winner,aligns,aligns_president
0,Delaware,DEM,DEM,DEM,True,True
1,Indiana,REP,REP,REP,True,True
2,Missouri,DEM,REP,REP,False,False
3,Montana,DEM,REP,REP,False,False
4,New Hampshire,REP,REP,DEM,True,False
5,North Carolina,DEM,DEM,REP,True,False
6,North Dakota,REP,REP,REP,True,True
7,Utah,REP,REP,REP,True,True
8,Vermont,REP,REP,DEM,True,False
9,Washington,DEM,DEM,DEM,True,True
10,West Virginia,REP,REP,REP,True,True

#### We further compared whether this earlier alignment reflected amongst the presidential elections. While the top 5 counties did sway the gubertorial elections to their dominant political party preference, this wasn't true for the presidential elections. Matter of fact, there's no strong correlation between the most influential counties' political party preferences and the outcome of the presidental election. This could be explained through the differences in impacts counties have on a their local vs. national elections. Furthermore, this highlights the importance of the public vote on a local and state level compared to the electoral college system the presidential election employs.